// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: planets.proto

package planets

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PlanetsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,3,opt,name=Name,proto3" json:"Name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlanetsRequest) Reset() {
	*x = PlanetsRequest{}
	mi := &file_planets_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlanetsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlanetsRequest) ProtoMessage() {}

func (x *PlanetsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_planets_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlanetsRequest.ProtoReflect.Descriptor instead.
func (*PlanetsRequest) Descriptor() ([]byte, []int) {
	return file_planets_proto_rawDescGZIP(), []int{0}
}

func (x *PlanetsRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type PlanetsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=Name,proto3" json:"Name,omitempty"`
	Type          string                 `protobuf:"bytes,4,opt,name=Type,proto3" json:"Type,omitempty"`
	Size          int32                  `protobuf:"varint,5,opt,name=Size,proto3" json:"Size,omitempty"`
	TempMin       int32                  `protobuf:"varint,6,opt,name=TempMin,proto3" json:"TempMin,omitempty"`
	TempMax       int32                  `protobuf:"varint,7,opt,name=TempMax,proto3" json:"TempMax,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlanetsResponse) Reset() {
	*x = PlanetsResponse{}
	mi := &file_planets_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlanetsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlanetsResponse) ProtoMessage() {}

func (x *PlanetsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_planets_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlanetsResponse.ProtoReflect.Descriptor instead.
func (*PlanetsResponse) Descriptor() ([]byte, []int) {
	return file_planets_proto_rawDescGZIP(), []int{1}
}

func (x *PlanetsResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PlanetsResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PlanetsResponse) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *PlanetsResponse) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *PlanetsResponse) GetTempMin() int32 {
	if x != nil {
		return x.TempMin
	}
	return 0
}

func (x *PlanetsResponse) GetTempMax() int32 {
	if x != nil {
		return x.TempMax
	}
	return 0
}

var File_planets_proto protoreflect.FileDescriptor

const file_planets_proto_rawDesc = "" +
	"\n" +
	"\rplanets.proto\x12\aplanets\x1a\x1cgoogle/api/annotations.proto\"$\n" +
	"\x0ePlanetsRequest\x12\x12\n" +
	"\x04Name\x18\x03 \x01(\tR\x04Name\"\x91\x01\n" +
	"\x0fPlanetsResponse\x12\x0e\n" +
	"\x02Id\x18\x01 \x01(\tR\x02Id\x12\x12\n" +
	"\x04Name\x18\x03 \x01(\tR\x04Name\x12\x12\n" +
	"\x04Type\x18\x04 \x01(\tR\x04Type\x12\x12\n" +
	"\x04Size\x18\x05 \x01(\x05R\x04Size\x12\x18\n" +
	"\aTempMin\x18\x06 \x01(\x05R\aTempMin\x12\x18\n" +
	"\aTempMax\x18\a \x01(\x05R\aTempMax2\x9d\x02\n" +
	"\x0ePlanetsService\x12T\n" +
	"\n" +
	"AllPlanets\x12\x17.planets.PlanetsRequest\x1a\x18.planets.PlanetsResponse\"\x13\x82\xd3\xe4\x93\x02\r\x12\v/v1/planets\x12Y\n" +
	"\n" +
	"HomePlanet\x12\x17.planets.PlanetsRequest\x1a\x18.planets.PlanetsResponse\"\x18\x82\xd3\xe4\x93\x02\x12\x12\x10/v1/planets/home\x12Z\n" +
	"\x06Update\x12\x17.planets.PlanetsRequest\x1a\x18.planets.PlanetsResponse\"\x1d\x82\xd3\xe4\x93\x02\x17:\x01*\"\x12/v1/planets/updateB\x0fZ\r./pkg;planetsb\x06proto3"

var (
	file_planets_proto_rawDescOnce sync.Once
	file_planets_proto_rawDescData []byte
)

func file_planets_proto_rawDescGZIP() []byte {
	file_planets_proto_rawDescOnce.Do(func() {
		file_planets_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_planets_proto_rawDesc), len(file_planets_proto_rawDesc)))
	})
	return file_planets_proto_rawDescData
}

var file_planets_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_planets_proto_goTypes = []any{
	(*PlanetsRequest)(nil),  // 0: planets.PlanetsRequest
	(*PlanetsResponse)(nil), // 1: planets.PlanetsResponse
}
var file_planets_proto_depIdxs = []int32{
	0, // 0: planets.PlanetsService.AllPlanets:input_type -> planets.PlanetsRequest
	0, // 1: planets.PlanetsService.HomePlanet:input_type -> planets.PlanetsRequest
	0, // 2: planets.PlanetsService.Update:input_type -> planets.PlanetsRequest
	1, // 3: planets.PlanetsService.AllPlanets:output_type -> planets.PlanetsResponse
	1, // 4: planets.PlanetsService.HomePlanet:output_type -> planets.PlanetsResponse
	1, // 5: planets.PlanetsService.Update:output_type -> planets.PlanetsResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_planets_proto_init() }
func file_planets_proto_init() {
	if File_planets_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_planets_proto_rawDesc), len(file_planets_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_planets_proto_goTypes,
		DependencyIndexes: file_planets_proto_depIdxs,
		MessageInfos:      file_planets_proto_msgTypes,
	}.Build()
	File_planets_proto = out.File
	file_planets_proto_goTypes = nil
	file_planets_proto_depIdxs = nil
}
